name: GitHub Runner Connectivity Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Check systemd-resolved status
        run: resolvectl status
      - name: Check connectivity
        run: |
          # Number of attempts
          max_attempts=10
          attempts=0

          # Function to perform nslookup
          perform_nslookup() {
              nslookup "$1"  # Replace "$1" with the desired domain or IP
          }

          # Main loop
          while (( attempts < max_attempts )); do
              perform_nslookup "ts-ubuntu-broken"  # You can replace "example.com" with your desired target
              exit_status=$?  # Capture exit status

              if [[ $exit_status -eq 0 ]]; then
                  echo "nslookup succeeded."
                  exit 0  # Exit the script if successful
              elif [[ $exit_status -eq 1 ]]; then
                  echo "nslookup failed. Retrying in 5 seconds..."
                  sleep 5  # Wait before retrying
                  ((attempts++))  # Increment the attempt counter
              else
                  echo "nslookup failed with exit status $exit_status."
                  exit $exit_status  # Exit with the actual status for other errors
              fi
          done

          echo "Maximum attempts reached. Exiting."
          exit 1
