name: GitHub Runner Connectivity Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - name: Symlink resolv.conf
        run: |
          ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
          ls -la /etc/resolv.conf
      - name: Connect to tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Check connectivity
        run: |
          i=0
          while [ $i -lt 10 ]; do
            nslookup ts-ubuntu-broken || {
              echo "DNS resolution failed, checking again in 5 seconds..."
              sleep 5
            }
            if [ $? -eq 0 ]; then
              exit 0 # Exit the script immediately after a successful lookup
            fi
            ((i++))
          done
